# Generated by Django 4.1.7 on 2023-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default='receptionist@maykin.com', max_length=255),
        ),
    ]
