# Generated by Django 4.1.7 on 2023-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0004_hotel_photo_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
